export const LOGIN_REQUEST = "AUTH.LOGIN_REQUEST";
export const LOGIN_SUCCESS = "AUTH.LOGIN_SUCCESS";
export const LOGIN_FAILURE = "AUTH.LOGIN_FAILURE";

export const GET_CURRENT_USER_REQUEST = "AUTH.GET_CURRENT_USER_REQUEST";
export const GET_CURRENT_USER_SUCCESS = "AUTH.GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAILURE = "AUTH.GET_CURRENT_USER_FAILURE";

export const LOGOUT = "AUTH.LOGOUT";

export const LOGIN_WITH_FB_REQUEST = "AUTH.LOGIN_WITH_FB_REQUEST";
export const LOGIN_WITH_FB_SUCCESS = "AUTH.LOGIN_WITH_FB_SUCCESS";
export const LOGIN_WITH_FB_FAILURE = "AUTH.LOGIN_WITH_FB_FAILURE";

export const LOGIN_WITH_GG_REQUEST = "AUTH.LOGIN_WITH_GG_REQUEST";
export const LOGIN_WITH_GG_SUCCESS = "AUTH.LOGIN_WITH_GG_SUCCESS";
export const LOGIN_WITH_GG_FAILURE = "AUTH.LOGIN_WITH_GG_FAILURE";
