export const ADD_BOOKING_REQUEST = "BOOKING.ADD_BOOKING_REQUEST";
export const ADD_BOOKING_SUCCESS = "BOOKING.ADD_BOOKING_SUCCESS";
export const ADD_BOOKING_FAILURE = "BOOKING.ADD_BOOKING_FAILURE";

export const GET_USER_BOOKING_REQUEST = "BOOKING.GET_USER_BOOKING_REQUEST";
export const GET_USER_BOOKING_SUCCESS = "BOOKING.GET_USER_BOOKING_SUCCESS";
export const GET_USER_BOOKING_FAILURE = "BOOKING.GET_USER_BOOKING_FAILURE";

export const PAYMENT_REQUEST = "BOOKING.PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "BOOKING.PAYMENT_SUCCESS";
export const PAYMENT_FAILURE = "BOOKING.PAYMENT_FAILURE";

export const GET_ALL_BOOKING_REQUEST = "BOOKING.GET_ALL_BOOKING_REQUEST";
export const GET_ALL_BOOKING_SUCCESS = "BOOKING.GET_ALL_BOOKING_SUCCESS";
export const GET_ALL_BOOKING_FAILURE = "BOOKING.GET_ALL_BOOKING_FAILURE";

export const UPDATE_BOOKING_STATUS_REQUEST =
  "BOOKING.UPDATE_BOOKING_STATUS_REQUEST";
export const UPDATE_BOOKING_STATUS_SUCCESS =
  "BOOKING.UPDATE_BOOKING_STATUS_SUCCESS";
export const UPDATE_BOOKING_STATUS_FAILURE =
  "BOOKING.UPDATE_BOOKING_STATUS_FAILURE";

export const SET_BOOKING_STAT_REQUEST = "BOOKING.SET_BOOKING_STAT_REQUEST";
export const SET_BOOKING_STAT_SUCCESS = "BOOKING.SET_BOOKING_STAT_SUCCESS";
export const SET_BOOKING_STAT_FAILURE = "BOOKING.SET_BOOKING_STAT_FAILURE";

export const CANCEL_PENDING_BOOKING_REQUEST =
  "BOOKING.CANCEL_PENDING_BOOKING_REQUEST";
export const CANCEL_PENDING_BOOKING_SUCCESS =
  "BOOKING.CANCEL_PENDING_BOOKING_SUCCESS";
export const CANCEL_PENDING_BOOKING_FAILURE =
  "BOOKING.CANCEL_PENDING_BOOKING_FAILURE";

export const GET_USER_PENDING_BOOKING_REQUEST =
  "BOOKING.GET_USER_PENDING_BOOKING_REQUEST";
export const GET_USER_PENDING_BOOKING_SUCCESS =
  "BOOKING.GET_USER_PENDING_BOOKING_SUCCESS";
export const GET_USER_PENDING_BOOKING_FAILURE =
  "BOOKING.GET_USER_PENDING_BOOKING_FAILURE";

export const CANCEL_ENTIRE_BOOKING_REQUEST =
  "BOOKING.CANCEL_ENTIRE_BOOKING_REQUEST";
export const CANCEL_ENTIRE_BOOKING_SUCCESS =
  "BOOKING.CANCEL_ENTIRE_BOOKING_SUCCESS";
export const CANCEL_ENTIRE_BOOKING_FAILURE =
  "BOOKING.CANCEL_ENTIRE_BOOKING_FAILURE";
