export const GET_EVENTS_REQUEST = "EVENT.GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "EVENT.GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "EVENT.GET_EVENTS_FAILURE";

export const GET_EVENTS_BYDATE_REQUEST = "EVENT.GET_EVENTS_BYDATE_REQUEST";
export const GET_EVENTS_BYDATE_SUCCESS = "EVENT.GET_EVENTS_BYDATE_SUCCESS";
export const GET_EVENTS_BYDATE_FAILURE = "EVENT.GET_EVENTS_BYDATE_FAILURE";

export const ADD_EVENT_REQUEST = "EVENT.ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "EVENT.ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILURE = "EVENT.ADD_EVENT_FAILURE";
