export const GET_RATINGS_REQUEST = "RATING.GET_RATINGS_REQUEST";
export const GET_RATINGS_SUCCESS = "RATING.GET_RATINGS_SUCCESS";
export const GET_RATINGS_FAILURE = "RATING.GET_RATINGS_FAILURE";

export const CREATE_RATING_REQUEST = "RATING.CREATE_RATING_REQUEST";
export const CREATE_RATING_SUCCESS = "RATING.CREATE_RATING_SUCCESS";
export const CREATE_RATING_FAILURE = "RATING.CREATE_RATING_FAILURE";
